// Generated by CoffeeScript 2.3.2
(function() {
  define(function() {
    var DevicesList;
    return DevicesList = class DevicesList {
      constructor(app) {
        this.app = app;
      }

      set(devices) {
        var a, d, name, results, template;
        $('#devices-list > *:not(template)').remove();
        template = $('#devices-list template').html();
        console.log(devices);
        results = [];
        for (name in devices) {
          d = devices[name];
          a = $(template);
          a.children('summary').html(name);
          results.push($('#devices-list').append(a));
        }
        return results;
      }

    };
  });

}).call(this);
