// Generated by CoffeeScript 1.9.3
(function() {
  define(function() {
    var Clues;
    return Clues = (function() {
      function Clues(app) {
        this.app = app;
      }

      Clues.prototype.set_propositions = function(messages) {
        var a, i, len, msg, results;
        $('#clues > div.list.select > *').remove();
        results = [];
        for (i = 0, len = messages.length; i < len; i++) {
          msg = messages[i];
          a = $('<span></span>');
          a.html(msg);
          a.click((function(_this) {
            return function(a) {
              return _this.set_content(a.target.innerHTML);
            };
          })(this));
          console.log(msg);
          results.push($('#clues > div.list.select').append(a));
        }
        return results;
      };

      Clues.prototype.set_content = function(msg) {
        return $('#clues textarea').val(msg);
      };

      return Clues;

    })();
  });

}).call(this);
