// Generated by CoffeeScript 1.9.3
(function() {
  define(function() {
    var Navigation;
    return Navigation = (function() {
      function Navigation(game_state) {
        this.game_state = game_state;
        window.addEventListener("hashchange", (function(_this) {
          return function() {
            return _this.navigate(_this.get_page_anchor());
          };
        })(this));
        this.navigate(this.get_page_anchor());
      }

      Navigation.prototype.get_page_anchor = function() {
        return window.location.href.split("#")[1];
      };

      Navigation.prototype.navigate = function(anchor) {
        $(".box nav > a").removeClass('active');
        $(".box nav > a[href='\#" + anchor + "']").addClass('active');
        $(".tab-content").removeClass('active');
        return $(".tab-content[id='tab-" + anchor + "']").addClass('active');
      };

      Navigation.prototype.set_game_is_running = function(is_running) {
        var a;
        a = $('.box nav > a.game_state');
        a.removeClass('loading');
        a.removeClass('new-game');
        a.removeClass('cancel-game');
        a.attr('href', null);
        if (is_running === void 0) {
          a.addClass('loading');
          return a.html('<div></div><div></div><div></div>');
        } else if (is_running) {
          a.addClass('cancel-game');
          return a.html('<img src="img/x_white.svg"/>Annuler la partie');
        } else {
          a.addClass('new-game');
          a.html('<img src="img/plus_white.svg"/>Nouvelle partie');
          return a.attr('href', '#setup');
        }
      };

      return Navigation;

    })();
  });

}).call(this);
